"""
conftest.py -- pytest fixtures for CNC trace log validation pipeline.

Usage:
    pytest test_pipeline.py -v -s --csv cnc_trace_log.csv
"""

import pytest
import pandas as pd
import numpy as np
from pathlib import Path


def pytest_addoption(parser):
    parser.addoption(
        "--trace-csv", action="store", default=None,
        help="Path to the CNC trace log CSV file (generated by sim mode)"
    )
    parser.addoption(
        "--csv-dir", action="store", default=None,
        help="Directory containing log_rtcp.csv, log_bspline.csv, log_g93.csv"
    )


@pytest.fixture(scope="session")
def csv_path(request):
    """Resolve CSV file path from command line or defaults."""
    path = request.config.getoption("--trace-csv")
    if path:
        return Path(path)
    return None


@pytest.fixture(scope="session")
def csv_dir(request):
    """Resolve CSV directory from command line or defaults."""
    path = request.config.getoption("--csv-dir")
    if path:
        return Path(path)
    # Default: project root
    return Path(__file__).resolve().parent.parent


def load_trace(csv_file: Path):
    """Load a single trace CSV and return data arrays."""
    df = pd.read_csv(csv_file)
    # Expected columns: cycle, virtual_time_ms, X, Y, Z, C, B, v_target
    cols = {c: df[c].values.astype(np.float64) for c in df.columns}
    return df, cols


def trim_active(arr, threshold=1e-8):
    """Remove leading/trailing zeros (system idle before/after motion)."""
    active = np.abs(arr) > threshold
    for c in ['X', 'Y', 'Z', 'B', 'C', 'v_target']:
        if c in arr if isinstance(arr, dict) else hasattr(arr, 'columns'):
            pass
    # Find first and last active point based on velocity or position change
    dx = np.diff(arr) if arr.ndim == 1 else np.sqrt(np.sum(np.diff(arr, axis=0)**2, axis=1))
    first = np.argmax(dx > 0)
    last = len(dx) - np.argmax(dx[::-1] > 0) - 1
    if first >= last:
        return np.arange(len(arr))
    return np.arange(max(0, first), min(len(arr), last + 2))
